<!--Task Navigation-->
<div class="big_wrapper">
<h1 class="sideh1">Task</h1>
<hr/>
<form method ="POST" action ="admin_home.php">
<a class="mdl_link" href="#" onclick="parentNode.submit()">
STUDENTS</a>
<input type="hidden" name="task" value="student" >
</form>

<form method ="POST" action ="admin_home.php">
<a class="mdl_link" href="#" onclick="parentNode.submit()">
LECTURERS</a>
<input type="hidden" name="task" value="lecturer" >
</form>

<form method ="POST" action ="admin_home.php">
<a class="mdl_link" href="#" onclick="parentNode.submit()">
MODULES</a>
<input type="hidden" name="task" value="module" >
</form>

<form method ="POST" action ="admin_home.php">
<a class="mdl_link" href="#" onclick="parentNode.submit()">
COURSES</a>
<input type="hidden" name="task" value="course" >
</form>

<form method ="POST" action ="admin_home.php">
<a class="mdl_link" href="#" onclick="parentNode.submit()">
ANNOUNCEMENTS</a>
<input type="hidden" name="task" value="announcement" >
</form>

<form method ="POST" action ="admin_home.php">
<a class="mdl_link" href="#" onclick="parentNode.submit()">
SETTINGS</a>
<input type="hidden" name="task" value="settings" >
</form>


</div>
<!--end Task Navigation-->