<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>MMS - Module Management System</title>
<meta name="keywords" content="module management system for student study in Nottingham University in Malaysia" />
<meta name="Student Module Management System" content="" />

<link rel="stylesheet" href="default_inter2.css" type="text/css">
</head>
<!--begin header -->
<div id="logo">
	<h1 align="right"><a href="#">MMS</a></h1>
	<p>Module Management System</p>
	<div id="logonot">
	<img src="images/logo.png" align="right">
	</div>
<a id="logoutlink" href="index.php">home</a>
<a> | </a>
<a id="logoutlink" href="logout.php">logout</a>	
</div>
<!--end header-->
<!-- begin page -->
<div id="page">
