
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>MMS - Module Management System</title>
<meta name="keywords" content="module management system for student study in Nottingham University in Malaysia" />
<meta name="Student Module Management System" content="" />
<link href="default_st.css" rel="stylesheet" type="text/css" media="screen" />

</head>
<body>
<!-- start header -->
<div id="logo">
	<h1 align="right"><a href="#">MMS</a></h1>
	<p>Module Management System</p>

	<div id="logonot">
	<img src="images/logo.png" align="right">
</div>
</div>

<!-- end header -->


<!-- end header -->
<div id="banner2">

</div>