<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>MMS - Module Management System</title>
<meta name="keywords" content="module management system for student study in Nottingham University in Malaysia" />
<meta name="Student Module Management System" content="" />

<link rel="stylesheet" href="default_inter2.css" type="text/css">
</head>
<!--begin header -->
<div id="logo">
	<h1 align="right"><a href="#">MMS</a></h1>
	<p>Module Management System</p>
	<div id="logonot">
	<img src="images/logo.png" align="right">
	</div>
<a id="logoutlink" href="#">home</a>
<a> | </a>
<a id="logoutlink" href="#">logout</a>	
</div>
<!--end header-->
<!-- begin page -->
<div id="page">
<h1>Result Report</h1>

<!--Report Detail -->

<h1 class="sideh1">G52IVG - Introduction to Visions and Graphic</h1>
<hr/>
<table width="1000" cellspacing="0" summary="Modulemark">
  <tr>
  <th scope="col" abbr="Name" class="nobg">Name</th>
  <th scope="col" abbr="CW1">CW1</th>
  <th scope="col" abbr="CW2">CW2</th>
  <th scope="col" abbr="EXAM">Exam</th>
  <th scope="col" abbr="Overall">Overall</th>
  </tr>
  <tr>
    <th scope="row" class="spec">Student A</th>
    <td>30</td>
    <td>30</td>
    <td>30</td>
    <td>30</td>
  </tr>
  <tr>
    <th scope="row" class="spec">Student B</th>
    <td>70</td>
    <td>70</td>
    <td>70</td>
    <td>70</td>
  </tr>
</table>
<br><br><br>
<!--Please make below auto calculated-->
<table width="250" cellspacing="0" summary="General">
  <tr>
    <th>Average</th>
    <th>Minimum</th>
    <th>Maximum</th>
  </tr>
  <tr>
    <td>50</td>
    <td>30</td>
    <td>70</td>
  </tr>
</table>
<br>

<!--end Report Detail -->
</div>
</body>
</html>