<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>MMS - Module Management System</title>
<meta name="keywords" content="module management system for student study in Nottingham University in Malaysia" />
<meta name="Student Module Management System" content="" />

<link rel="stylesheet" href="default_inter2.css" type="text/css">
</head>
<!--begin header -->
<div id="logo">
	<h1 align="right"><a href="#">MMS</a></h1>
	<p>Module Management System</p>
	<div id="logonot">
	<img src="images/logo.png" align="right">
	</div>
<a id="logoutlink" href="#">home</a>
<a> | </a>
<a id="logoutlink" href="#">logout</a>	
</div>
<!--end header-->
<!-- begin page -->
<div id="page">
<h1>Attendance</h1>

<!--Report Detail -->

<h1 class="sideh1">G52IVG - Introduction to Visions and Graphic</h1>
<hr/>
<table width="1000" cellspacing="0" summary="Modulemark">
  <tr>
  <th scope="col" abbr="No." class="nobg">No.</th>
  <th scope="col" abbr="Name">Name</th>
  <th scope="col" abbr="ID">ID</th>
  <th scope="col" abbr="sign">Signature</th>
  </tr>
  <tr>
    <td>1</td>
    <td>Student A</td>
    <td>004433</td>
    <td></td>
  </tr>
  <tr>
    <td>2</td>
    <td>Student B</td>
    <td>003352</td>
    <td></td>
  </tr>
</table>
<p>Date:</p>
<!--end Report Detail -->
</div>
</body>
</html>